### PR TITLE
Upgrade to ShipService_v26 and RateService_v28

### PR DESCRIPTION
**Pull request by Linekio**
Fix https://github.com/python-fedex-devs/python-fedex/issues/154

### CODE REVIEW

**Review by radzhome — APPROVED** [review]

**Comment by radzhome** [comment]
Hey did anyone see if the tests are all passing? Any updates to tests?

**Review by radzhome — COMMENTED** [review]
Would need to run tests, make sure nothing broke.. any new features needs to be added to tests?

**Comment by Linekio** [comment]
Hi,
- I just rebased the branch
- I ran tests :
```
$ python -m unittest
ss.sssssssss.s
----------------------------------------------------------------------
Ran 14 tests in 0.217s

OK (skipped=12)
```

**Comment by isdabenx** [comment]
How can I help so that this is in the master branch?

**Comment by IrinaAlexandra** [comment]
any updates on this?

**Comment by isdabenx** [comment]
@radzhome How can I help so that this is in the master branch?

**Pull request merged**
